### ISSUE TITLE
No de-duplication when backend is offline

### ISSUE THREAD

**Issue by SammyDelanghe** [12urenloop/manual-count-2#50] opened 2022-03-12 08:37 UTC
When the backend of manual count is offline:
* there is no de-duplication of the laps atm: within 15 seconds it should only be possible to ad 1 lap to a team
* the de-duplication rule above should also work with multiple users are counting laps

**Comment by redfast00** [comment] 2022-03-12 09:08
manual count could/should in broad terms work like the stations do and be pull based instead of push based. the problem is that browsers don't make pull-based api's easy, but the data flow conceptually could work like this

**Comment by redfast00** [comment] 2022-03-12 09:08
I'll look into it after the OBUS event

**Comment by NuttyShrimp** [comment] 2022-03-12 12:48
I've changed the search query for interfering laps in #49, now it searches for a lap at the timestamp of the pushed lap + and - the min difference needed between two laps

**Comment by NuttyShrimp** [comment] 2022-03-16 07:38
So for caching the laps on the client and moving to a pull based system following tasks must be done:

Moved to #55

**Closed as completed** 2023-02-03 11:21 UTC
Labels: Priority: Critical
